services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app/bot
      - ./core:/app/core
      - ./db:/app/db
      - ./monitor:/app/monitor
    env_file:
      - .env
    depends_on:
      - monitor
      - db

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    volumes:
      - ./monitor:/app/monitor
      - ./core:/app/core
      - ./db:/app/db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Убедитесь, что это корректно настроено
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
